### ISSUE TITLE
Remove supervisord

### ISSUE THREAD

**Issue by wagoodman** [EugenMayer/docker-image-unison#2]
Currently the entrypoint is supervisord, allowing multiple processes to run in a container. Running multiple processes itself is not bad, however, with the current configuration this is a Docker anti-pattern (https://github.com/docker/docker.github.io/pull/3026). This is a good practice for grounded reasons as exited/failed subprocesses are not easily observable. Case in point, we've been having phantom docker-sync issues which we eventually tracked back to unison failing within the container this repo provides. This would have been more easily found if the container stopped with the failing unison process, as any application container should do.

Looking at the configuration for this repo I see that Monit prevents removing supervisord. I'd suggest one of two approaches:
- remove monit (probably not preferred if many users are using this feature)
- configure supervisord to exit upon unison failing/exiting. Something like this https://blog.zhaw.ch/icclab/process-management-in-docker-containers/ (though I'm not in love with this approach)

What is your take @EugenMayer on the two approaches above? I'd be open to more suggestions, and additionally, I'd be willing to put in a PR.

**Comment by EugenMayer** [comment]
@wagoodman thank you for your suggestions. Please do not create a PR for this or start working ont htis, this is nothing i would ever merge.

Supervisor is in no way a docker-antipattern as long as one knows how to handle it. And having a non-restartable / recoverable unison daemon in that scenario with docker-sync will have far worse implication.

Removing monit would be about the opposite i would go for, its the single most best improvement we can introduce in the recent features added. (since both unison and the docker engine on d4m is unreliable )

Handling processes with supervisor is rock-solid unless everybody understands, what `exec` means, how to handle traps, what a subprocess is an much more. Starting something with `bash -l -c "do that"` in supervisor leads to a subprocess and an issue, while `exec bash..` does not. One can use traps to work arround the usage of `exec` too.

Beside that, supervisor is an absolute substantial mechanic in here to avoid the bash variable substitution hell.
