### ISSUE TITLE
problem with sync on M1

### ISSUE THREAD

**Issue by EspertoMagento** [EugenMayer/docker-image-unison#26]
Hello,
I used your docker repository to solve my docker-sync problem on Apple M1.

Now I'm not getting errors like before, but the data doesn't sync. 
My situation is:
the directory that I have to synchronize in my local environment is called: **magento**
I have to sync it with the directory in the docker container in: **/var/www/html/**

**What** and **where** I have to write the variable **APP_VOLUME** to sync the directory correctly?

Thanks! :)

**Comment by yosephsa** [comment]
I assume you are using docker sync, be sure to follow this guide https://docker-sync.readthedocs.io/en/latest/getting-started/configuration.html

Essentially you'll have a `docker-sync.yml` and a `docker-compose.yml` file where you'll put your changes according to the docs and that should do the trick when you run `docker-sync start`. 
- The compose file will define that you are using docker-sync and where to sync into the container. 
- The `docker-sync.yml` will define the directory of the sync on your host machine.

If you keep having issues, you should post an issue on Docker Sync repo https://github.com/EugenMayer/docker-sync instead of this one.

**Comment by EugenMayer** [comment]
superseeded by #27 and #30
